name: Daily Append Date

on:
  schedule:
    - cron: '06 13 * * *'

jobs:
  append-date:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Append date to txt file for daniel.putta@gramener.com
        run: |
          echo "$(date)" >> timestamp.txt
